version: "3.8"
services:
  my-mysql-0:
    image: mysql:8.0.23
    container_name: my-mysql-0
    restart: "no"
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: hl
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'password'
    command: >
      --general-log=ON
      --log-queries-not-using-indexes=ON
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 384M
    networks:
      ab_subnet:
        aliases:
          - my-mysql-1.localhost
    ports:
      - 3360:3306
    volumes:
      - my-mysql-0-data:/var/lib/mysql
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
      - /Users/a18578179/docker/volumes/my-mysql-0/conf.d:/etc/mysql/conf.d

  my-mysql-1:
    image: mysql:8.0.23
    container_name: my-mysql-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: hl
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'password'
    command: >
      --general-log=ON
      --log-queries-not-using-indexes=ON
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 384M
    networks:
      ab_subnet:
        aliases:
          - my-mysql-1.localhost
    ports:
      - 3361:3306
    volumes:
      - my-mysql-1-data:/var/lib/mysql
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
      - /Users/a18578179/docker/volumes/my-mysql-1/conf.d:/etc/mysql/conf.d

  my-mysql-2:
    image: mysql:8.0.23
    container_name: my-mysql-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: hl
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'password'
    command: >
      --general-log=ON
      --log-queries-not-using-indexes=ON
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 384M
    networks:
      ab_subnet:
        aliases:
          - my-mysql-2.localhost
    ports:
      - 3362:3306
    volumes:
      - my-mysql-2-data:/var/lib/mysql
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
      - /Users/a18578179/docker/volumes/my-mysql-2/conf.d:/etc/mysql/conf.d

  my-haproxy:
    image: haproxy:2.1.7
    container_name: haproxy-lb
    restart: "no"
    depends_on:
      - my-mysql-0
      - my-mysql-1
      - my-mysql-2
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          memory: 128M
    networks:
      ab_subnet:
        aliases:
          - my-haproxy.localhost
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "3306:3306"
      - "8404:8404"

  my-app-dialog-1:
    image: vskurikhin/app-dialog-amd64
    container_name: my-app-dialog-1
    restart: "no"
    depends_on:
      - my-haproxy
    environment:
      DB_HOST_RW: my-mysql-0
      DB_PORT_RW: 3306
      DB_HOST_RO: my-haproxy
      DB_PORT_RO: 3306
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
    networks:
      - ab_subnet

  my-app-dialog-2:
    image: vskurikhin/app-dialog-amd64
    container_name: my-app-dialog-2
    restart: "no"
    depends_on:
      - my-haproxy
    environment:
      DB_HOST_RW: my-mysql-0
      DB_PORT_RW: 3306
      DB_HOST_RO: my-haproxy
      DB_PORT_RO: 3306
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
    networks:
      - ab_subnet

  my-app-main-1:
    image: vskurikhin/app-main-amd64
    container_name: my-app-main-1
    restart: "no"
    depends_on:
      - my-haproxy
    environment:
      DB_HOST_RW: my-mysql-0
      DB_PORT_RW: 3306
      DB_HOST_RO: my-haproxy
      DB_PORT_RO: 3306
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
    networks:
      - ab_subnet

  my-app-main-2:
    image: vskurikhin/app-main-amd64
    container_name: my-app-main-2
    restart: "no"
    depends_on:
      - my-haproxy
    environment:
      DB_HOST_RW: my-mysql-0
      DB_PORT_RW: 3306
      DB_HOST_RO: my-haproxy
      DB_PORT_RO: 3306
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
    networks:
      - ab_subnet

  my-nginx:
    image: nginx:1.19.0
    container_name: nginx-lb
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
    networks:
      - ab_subnet
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
      - "8888:8888"

  my-cdc-producer:
    image: vskurikhin/cdc-producer
    container_name: my-cdc-producer
    restart: on-failure
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_HOSTNAME: my-mysql-0
      DATABASE_PORT: 3306
      DEBEZIUM_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      ab_subnet:
        aliases:
          - my-cdc-producer.localhost
        ipv4_address: 172.16.1.218


volumes:
  my-mysql-0-data:
  my-mysql-1-data:
  my-mysql-2-data:

networks:
  ab_subnet:
    external: true
