{
 "title": "Nginx",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(nginx_up,job)" },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(nginx_up{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(nginx_up{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Status ",
   "type": "singlestat",
   "description": "Source\nhttps://github.com/nginxinc/nginx-prometheus-exporter/tree/master/grafana",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed Connections",
   "type": "graph",
   "description": "The number of accepted and handled connections as irate in a range of 5 minutes.\n\nAccepts:\nThe total number of accepted client connections.\n\nHandled: \nThe total number of handled connections.\n\nGenerally, the parameter value is the same as accepts unless some resource limits have been reached (for example, the worker_connections limit). \n\n",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$node:$port\",job=\"$job\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$node:$port\",job=\"$job\"}[5m])",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Reading : \nThe current number of connections where nginx is reading the request header.\n\nWriting:\n The current number of connections where nginx is writing the response back to the client. \n\nWaiting:\nThe current number of idle client connections waiting for a request. \n\nActive connections:\nThe current number of active client connections including Waiting connections. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Writing"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$node:$port\",job=\"$job\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "The total number of client requests as irate in a range of 5 minutes.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$node:$port\",job=\"$job\"}[5m])",
     "legendFormat": "Total Requests"
    }
   ]
  }
 ]
}