apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-reads
  namespace: default
spec:
  externalIPs:
    - 192.168.88.88
  externalTrafficPolicy: Cluster
  ports:
    - port: 3305
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer