apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-0
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    nodePort: 30360
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: mysql-0
  type: NodePort
