kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    app: mysql
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/mysql"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
