CREATE DATABASE IF NOT EXISTS hl DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
CREATE USER 'hl'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE VIEW, REFERENCES, INDEX, DROP, ALTER, EXECUTE, TRIGGER, CREATE TEMPORARY TABLES, LOCK TABLES ON hl.* TO 'hl'@'localhost';
