export const SEX_OPTIONS = [
    {
        key: 'male',
        text: 'Male',
        value: '0',
    },
    {
        key: 'female',
        text: 'Female',
        value: '1',
    },
]

export const CITY_OPTIONS = [
    { flag: 'af', key: 'Абу-Даби',                     value: 'Абу-Даби',                     text: 'Абу-Даби' },
    { flag: 'ax', key: 'Абуджа',                       value: 'Абуджа',                       text: 'Абуджа' },
    { flag: 'al', key: 'Аддис-Абеба',                  value: 'Аддис-Абеба',                  text: 'Аддис-Абеба' },
    { flag: 'dz', key: 'Аккра',                        value: 'Аккра',                        text: 'Аккра' },
    { flag: 'as', key: 'Алжир',                        value: 'Алжир',                        text: 'Алжир' },
    { flag: 'ad', key: 'Амман',                        value: 'Амман',                        text: 'Амман' },
    { flag: 'ao', key: 'Амстердам',                    value: 'Амстердам',                    text: 'Амстердам' },
    { flag: 'ai', key: 'Андорра-ла-Велья',             value: 'Андорра-ла-Велья',             text: 'Андорра-ла-Велья' },
    { flag: 'ag', key: 'Анкара',                       value: 'Анкара',                       text: 'Анкара' },
    { flag: 'ar', key: 'Антананариву',                 value: 'Антананариву',                 text: 'Антананариву' },
    { flag: 'am', key: 'Апиа',                         value: 'Апиа',                         text: 'Апиа' },
    { flag: 'aw', key: 'Асмэра',                       value: 'Асмэра',                       text: 'Асмэра' },
    { flag: 'au', key: 'Астана',                       value: 'Астана',                       text: 'Астана' },
    { flag: 'at', key: 'Асунсьон',                     value: 'Асунсьон',                     text: 'Асунсьон' },
    { flag: 'az', key: 'Афины',                        value: 'Афины',                        text: 'Афины' },
    { flag: 'bs', key: 'Ашхабад',                      value: 'Ашхабад',                      text: 'Ашхабад' },
    { flag: 'bh', key: 'Багдад',                       value: 'Багдад',                       text: 'Багдад' },
    { flag: 'bd', key: 'Баку',                         value: 'Баку',                         text: 'Баку' },
    { flag: 'bb', key: 'Бамако',                       value: 'Бамако',                       text: 'Бамако' },
    { flag: 'by', key: 'Банги',                        value: 'Банги',                        text: 'Банги' },
    { flag: 'be', key: 'Бангкок',                      value: 'Бангкок',                      text: 'Бангкок' },
    { flag: 'bz', key: 'Бандар-Сери-Багаван',          value: 'Бандар-Сери-Багаван',          text: 'Бандар-Сери-Багаван' },
    { flag: 'bj', key: 'Банжул',                       value: 'Банжул',                       text: 'Банжул' },
    { flag: 'kn', key: 'Бастер',                       value: 'Бастер',                       text: 'Бастер' },
    { flag: 'lb', key: 'Бейрут',                       value: 'Бейрут',                       text: 'Бейрут' },
    { flag: 'cs', key: 'Белград',                      value: 'Белград',                      text: 'Белград' },
    { flag: 'bz', key: 'Бельмопан',                    value: 'Бельмопан',                    text: 'Бельмопан' },
    { flag: 'de', key: 'Берлин',                       value: 'Берлин',                       text: 'Берлин' },
    { flag: 'ch', key: 'Берн',                         value: 'Берн',                         text: 'Берн' },
    { flag: 'gw', key: 'Бисау',                        value: 'Бисау',                        text: 'Бисау' },
    { flag: 'kg', key: 'Бишкек',                       value: 'Бишкек',                       text: 'Бишкек' },
    { flag: 'cg', key: 'Браззавиль',                   value: 'Браззавиль',                   text: 'Браззавиль' },
    { flag: 'br', key: 'Бразилиа',                     value: 'Бразилиа',                     text: 'Бразилиа' },
    { flag: 'sk', key: 'Братислава',                   value: 'Братислава',                   text: 'Братислава' },
    { flag: 'bb', key: 'Бриджтаун',                    value: 'Бриджтаун',                    text: 'Бриджтаун' },
    { flag: 'be', key: 'Брюссель',                     value: 'Брюссель',                     text: 'Брюссель' },
    { flag: 'hu', key: 'Будапешт',                     value: 'Будапешт',                     text: 'Будапешт' },
    { flag: 'bi', key: 'Бужумбура',                    value: 'Бужумбура',                    text: 'Бужумбура' },
    { flag: 'ro', key: 'Бухарест',                     value: 'Бухарест',                     text: 'Бухарест' },
    { flag: 'ar', key: 'Буэнос-Айр',                   value: 'Буэнос-Айр',                   text: 'Буэнос-Айр' },
    { flag: 'li', key: 'Вадуц',                        value: 'Вадуц',                        text: 'Вадуц' },
    { flag: 'mt', key: 'Валлетта',                     value: 'Валлетта',                     text: 'Валлетта' },
    { flag: 'pl', key: 'Варшава',                      value: 'Варшава',                      text: 'Варшава' },
    { flag: 'va', key: 'Ватикан',                      value: 'Ватикан',                      text: 'Ватикан' },
    { flag: 'us', key: 'Вашингтон',                    value: 'Вашингтон',                    text: 'Вашингтон' },
    { flag: 'nz', key: 'Веллингтон',                   value: 'Веллингтон',                   text: 'Веллингтон' },
    { flag: 'at', key: 'Вена',                         value: 'Вена',                         text: 'Вена' },
    { flag: 'sc', key: 'Виктория',                     value: 'Виктория',                     text: 'Виктория' },
    { flag: 'lt', key: 'Вильнюс',                      value: 'Вильнюс',                      text: 'Вильнюс' },
    { flag: 'na', key: 'Виндхук',                      value: 'Виндхук',                      text: 'Виндхук' },
    { flag: 'la', key: 'Вьентьян',                     value: 'Вьентьян',                     text: 'Вьентьян' },
    { flag: 'bw', key: 'Габороне',                     value: 'Габороне',                     text: 'Габороне' },
    { flag: 'cu', key: 'Гавана',                       value: 'Гавана',                       text: 'Гавана' },
    { flag: 'gt', key: 'Гватемала',                    value: 'Гватемала',                    text: 'Гватемала' },
    { flag: 'sn', key: 'Дакар',                        value: 'Дакар',                        text: 'Дакар' },
    { flag: 'bd', key: 'Дакка',                        value: 'Дакка',                        text: 'Дакка' },
    { flag: 'sy', key: 'Дамаск',                       value: 'Дамаск',                       text: 'Дамаск' },
    { flag: 'id', key: 'Джакарта',                     value: 'Джакарта',                     text: 'Джакарта' },
    { flag: 'dj', key: 'Джибути',                      value: 'Джибути',                      text: 'Джибути' },
    { flag: 'gy', key: 'Джорджтаун',                   value: 'Джорджтаун',                   text: 'Джорджтаун' },
    // { flag: 'tp', key: 'Дили',                         value: 'Дили',                         text: 'Дили' },
    { flag: 'tz', key: 'Додома',                       value: 'Додома',                       text: 'Додома' },
    { flag: 'qa', key: 'Доха',                         value: 'Доха',                         text: 'Доха' },
    { flag: 'bj', key: 'Дублин',                       value: 'Дублин',                       text: 'Дублин' },
    { flag: 'bj', key: 'Душанбе',                      value: 'Душанбе',                      text: 'Душанбе' },
    { flag: 'bj', key: 'Ереван',                       value: 'Ереван',                       text: 'Ереван' },
    { flag: 'bj', key: 'Загреб',                       value: 'Загреб',                       text: 'Загреб' },
    { flag: 'bj', key: 'Иерусалим',                    value: 'Иерусалим',                    text: 'Иерусалим' },
    { flag: 'bj', key: 'Исламабад',                    value: 'Исламабад',                    text: 'Исламабад' },
    { flag: 'bj', key: 'Кабул',                        value: 'Кабул',                        text: 'Кабул' },
    { flag: 'bj', key: 'Каир',                         value: 'Каир',                         text: 'Каир' },
    { flag: 'bj', key: 'Кампала',                      value: 'Кампала',                      text: 'Кампала' },
    { flag: 'bj', key: 'Канберра',                     value: 'Канберра',                     text: 'Канберра' },
    { flag: 'bj', key: 'Каракас',                      value: 'Каракас',                      text: 'Каракас' },
    { flag: 'bj', key: 'Кастри',                       value: 'Кастри',                       text: 'Кастри' },
    { flag: 'bj', key: 'Катманду',                     value: 'Катманду',                     text: 'Катманду' },
    { flag: 'bj', key: 'Кигали',                       value: 'Кигали',                       text: 'Кигали' },
    { flag: 'bj', key: 'Киев',                         value: 'Киев',                         text: 'Киев' },
    { flag: 'bj', key: 'Кингстаун',                    value: 'Кингстаун',                    text: 'Кингстаун' },
    { flag: 'bj', key: 'Кингстон',                     value: 'Кингстон',                     text: 'Кингстон' },
    { flag: 'bj', key: 'Киншаса',                      value: 'Киншаса',                      text: 'Киншаса' },
    { flag: 'bj', key: 'Кито',                         value: 'Кито',                         text: 'Кито' },
    { flag: 'bj', key: 'Кишинев',                      value: 'Кишинев',                      text: 'Кишинев' },
    { flag: 'lk', key: 'Коломбо',                      value: 'Коломбо',                      text: 'Коломбо' },
    { flag: 'gn', key: 'Конакри',                      value: 'Конакри',                      text: 'Конакри' },
    { flag: 'dk', key: 'Копенгаген',                   value: 'Копенгаген',                   text: 'Копенгаген' },
    { flag: 'my', key: 'Куала-Лумпур',                 value: 'Куала-Лумпур',                 text: 'Куала-Лумпур' },
    { flag: 'ga', key: 'Либревиль',                    value: 'Либревиль',                    text: 'Либревиль' },
    { flag: 'mw', key: 'Лилонгве',                     value: 'Лилонгве',                     text: 'Лилонгве' },
    { flag: 'pe', key: 'Лима',                         value: 'Лима',                         text: 'Лима' },
    { flag: 'pt', key: 'Лиссабон',                     value: 'Лиссабон',                     text: 'Лиссабон' },
    { flag: 'tg', key: 'Ломе',                         value: 'Ломе',                         text: 'Ломе' },
    { flag: 'uk', key: 'Лондон',                       value: 'Лондон',                       text: 'Лондон' },
    { flag: 'ao', key: 'Луанда',                       value: 'Луанда',                       text: 'Луанда' },
    { flag: 'zm', key: 'Лусака',                       value: 'Лусака',                       text: 'Лусака' },
    { flag: 'si', key: 'Любляна',                      value: 'Любляна',                      text: 'Любляна' },
    { flag: 'lu', key: 'Люксембург',                   value: 'Люксембург',                   text: 'Люксембург' },
    { flag: 'mh', key: 'Маджуро',                      value: 'Маджуро',                      text: 'Маджуро' },
    { flag: 'es', key: 'Мадрид',                       value: 'Мадрид',                       text: 'Мадрид' },
    { flag: 'gq', key: 'Малабо',                       value: 'Малабо',                       text: 'Малабо' },
    { flag: 'mv', key: 'Мале',                         value: 'Мале',                         text: 'Мале' },
    { flag: 'ni', key: 'Манагуа',                      value: 'Манагуа',                      text: 'Манагуа' },
    { flag: 'bh', key: 'Манама',                       value: 'Манама',                       text: 'Манама' },
    { flag: 'ph', key: 'Манила',                       value: 'Манила',                       text: 'Манила' },
    { flag: 'mz', key: 'Мапуту',                       value: 'Мапуту',                       text: 'Мапуту' },
    { flag: 'ls', key: 'Масеру',                       value: 'Масеру',                       text: 'Масеру' },
    { flag: 'om', key: 'Маскат',                       value: 'Маскат',                       text: 'Маскат' },
    { flag: 'sz', key: 'Мбабане',                      value: 'Мбабане',                      text: 'Мбабане' },
    { flag: 'pw', key: 'Мелекеок',                     value: 'Мелекеок',                     text: 'Мелекеок' },
    { flag: 'mx', key: 'Мехико',                       value: 'Мехико',                       text: 'Мехико' },
    { flag: 'by', key: 'Минск',                        value: 'Минск',                        text: 'Минск' },
    { flag: 'so', key: 'Могадишо',                     value: 'Могадишо',                     text: 'Могадишо' },
    { flag: 'mc', key: 'Монако',                       value: 'Монако',                       text: 'Монако' },
    { flag: 'lr', key: 'Монровия',                     value: 'Монровия',                     text: 'Монровия' },
    { flag: 'uy', key: 'Монтевидео',                   value: 'Монтевидео',                   text: 'Монтевидео' },
    { flag: 'km', key: 'Морони',                       value: 'Морони',                       text: 'Морони' },
    { flag: 'ru', key: 'Москва',                       value: 'Москва',                       text: 'Москва' },
    { flag: 'mm', key: 'Найпьидо',                     value: 'Найпьидо',                     text: 'Найпьидо' },
    { flag: 'ke', key: 'Найроби',                      value: 'Найроби',                      text: 'Найроби' },
    { flag: 'bs', key: 'Нассау',                       value: 'Нассау',                       text: 'Нассау' },
    { flag: 'td', key: 'Нджамена',                     value: 'Нджамена',                     text: 'Нджамена' },
    { flag: 'ne', key: 'Ниамей',                       value: 'Ниамей',                       text: 'Ниамей' },
    { flag: 'cy', key: 'Никосия',                      value: 'Никосия',                      text: 'Никосия' },
    { flag: 'mr', key: 'Нуакшот',                      value: 'Нуакшот',                      text: 'Нуакшот' },
    { flag: 'to', key: 'Нукуалофа',                    value: 'Нукуалофа',                    text: 'Нукуалофа' },
    { flag: 'in', key: 'Нью-Дели',                     value: 'Нью-Дели',                     text: 'Нью-Дели' },
    { flag: 'no', key: 'Осло',                         value: 'Осло',                         text: 'Осло' },
    { flag: 'ca', key: 'Оттава',                       value: 'Оттава',                       text: 'Оттава' },
    { flag: 'nr', key: 'официальной столицы не имеет', value: 'официальной столицы не имеет', text: 'официальной столицы не имеет' },
    { flag: 'fm', key: 'Паликир',                      value: 'Паликир',                      text: 'Паликир' },
    { flag: 'pa', key: 'Панама',                       value: 'Панама',                       text: 'Панама' },
    { flag: 'sr', key: 'Парамарибо',                   value: 'Парамарибо',                   text: 'Парамарибо' },
    { flag: 'fr', key: 'Париж',                        value: 'Париж',                        text: 'Париж' },
    { flag: 'cn', key: 'Пекин',                        value: 'Пекин',                        text: 'Пекин' },
    { flag: 'kh', key: 'Пномпень',                     value: 'Пномпень',                     text: 'Пномпень' },
    // { flag: 'yu', key: 'Подгорица',                    value: 'Подгорица',                    text: 'Подгорица' },
    { flag: 'vu', key: 'Порт-Вила',                    value: 'Порт-Вила',                    text: 'Порт-Вила' },
    { flag: 'mu', key: 'Порт-Луи',                     value: 'Порт-Луи',                     text: 'Порт-Луи' },
    { flag: 'pg', key: 'Порт-Морсби',                  value: 'Порт-Морсби',                  text: 'Порт-Морсби' },
    { flag: 'ht', key: 'Порт-о-Пренс',                 value: 'Порт-о-Пренс',                 text: 'Порт-о-Пренс' },
    { flag: 'tt', key: 'Порт-оф-Спейн',                value: 'Порт-оф-Спейн',                text: 'Порт-оф-Спейн' },
    { flag: 'bj', key: 'Порто-Ново',                   value: 'Порто-Ново',                   text: 'Порто-Ново' },
    { flag: 'cz', key: 'Прага',                        value: 'Прага',                        text: 'Прага' },
    { flag: 'cv', key: 'Прая',                         value: 'Прая',                         text: 'Прая' },
    { flag: 'za', key: 'Претория',                     value: 'Претория',                     text: 'Претория' },
    { flag: 'kp', key: 'Пхеньян',                      value: 'Пхеньян',                      text: 'Пхеньян' },
    { flag: 'ma', key: 'Рабат',                        value: 'Рабат',                        text: 'Рабат' },
    { flag: 'is', key: 'Рейкьявик',                    value: 'Рейкьявик',                    text: 'Рейкьявик' },
    { flag: 'lv', key: 'Рига',                         value: 'Рига',                         text: 'Рига' },
    { flag: 'it', key: 'Рим',                          value: 'Рим',                          text: 'Рим' },
    { flag: 'dm', key: 'Розо',                         value: 'Розо',                         text: 'Розо' },
    { flag: 'sm', key: 'Сан-Марино',                   value: 'Сан-Марино',                   text: 'Сан-Марино' },
    { flag: 'sv', key: 'Сан-Сальвадор',                value: 'Сан-Сальвадор',                text: 'Сан-Сальвадор' },
    { flag: 'st', key: 'Сан-Томе',                     value: 'Сан-Томе',                     text: 'Сан-Томе' },
    { flag: 'cr', key: 'Сан-Хосе',                     value: 'Сан-Хосе',                     text: 'Сан-Хосе' },
    { flag: 'ye', key: 'Сана',                         value: 'Сана',                         text: 'Сана' },
    { flag: 'co', key: 'Санта-Фе-де-Богота',           value: 'Санта-Фе-де-Богота',           text: 'Санта-Фе-де-Богота' },
    { flag: 'do', key: 'Санто-Доминго',                value: 'Санто-Доминго',                text: 'Санто-Доминго' },
    { flag: 'cl', key: 'Сантьяго',                     value: 'Сантьяго',                     text: 'Сантьяго' },
    { flag: 'ba', key: 'Сараево',                      value: 'Сараево',                      text: 'Сараево' },
    { flag: 'ag', key: 'Сент-Джонс',                   value: 'Сент-Джонс',                   text: 'Сент-Джонс' },
    { flag: 'gd', key: 'Сент-Джорджес',                value: 'Сент-Джорджес',                text: 'Сент-Джорджес' },
    { flag: 'kr', key: 'Сеул',                         value: 'Сеул',                         text: 'Сеул' },
    { flag: 'sg', key: 'Сингапур',                     value: 'Сингапур',                     text: 'Сингапур' },
    { flag: 'mk', key: 'Скопье',                       value: 'Скопье',                       text: 'Скопье' },
    { flag: 'bg', key: 'София',                        value: 'София',                        text: 'София' },
    { flag: 'se', key: 'Стокгольм',                    value: 'Стокгольм',                    text: 'Стокгольм' },
    { flag: 'fj', key: 'Сува',                         value: 'Сува',                         text: 'Сува' },
    { flag: 'bo', key: 'Сукре',                        value: 'Сукре',                        text: 'Сукре' },
    { flag: 'ee', key: 'Таллин',                       value: 'Таллин',                       text: 'Таллин' },
    { flag: 'uz', key: 'Ташкент',                      value: 'Ташкент',                      text: 'Ташкент' },
    { flag: 'ge', key: 'Тбилиси',                      value: 'Тбилиси',                      text: 'Тбилиси' },
    { flag: 'ir', key: 'Тегеран',                      value: 'Тегеран',                      text: 'Тегеран' },
    { flag: 'hn', key: 'Тегусигальпа',                 value: 'Тегусигальпа',                 text: 'Тегусигальпа' },
    { flag: 'al', key: 'Тирана',                       value: 'Тирана',                       text: 'Тирана' },
    { flag: 'jp', key: 'Токио',                        value: 'Токио',                        text: 'Токио' },
    { flag: 'ly', key: 'Триполи',                      value: 'Триполи',                      text: 'Триполи' },
    { flag: 'tn', key: 'Тунис',                        value: 'Тунис',                        text: 'Тунис' },
    { flag: 'bt', key: 'Тхимпху',                      value: 'Тхимпху',                      text: 'Тхимпху' },
    { flag: 'bf', key: 'Уагадугу',                     value: 'Уагадугу',                     text: 'Уагадугу' },
    { flag: 'mn', key: 'Улан-Батор',                   value: 'Улан-Батор',                   text: 'Улан-Батор' },
    { flag: 'sl', key: 'Фритаун',                      value: 'Фритаун',                      text: 'Фритаун' },
    { flag: 'tv', key: 'Фунафути',                     value: 'Фунафути',                     text: 'Фунафути' },
    { flag: 'vn', key: 'Ханой',                        value: 'Ханой',                        text: 'Ханой' },
    { flag: 'zw', key: 'Хараре',                       value: 'Хараре',                       text: 'Хараре' },
    { flag: 'zw', key: 'Хартум',                       value: 'Хартум',                       text: 'Хартум' },
    { flag: 'fi', key: 'Хельсинки',                    value: 'Хельсинки',                    text: 'Хельсинки' },
    { flag: 'sb', key: 'Хониара',                      value: 'Хониара',                      text: 'Хониара' },
    { flag: 'kw', key: 'Эль-Кувейт',                   value: 'Эль-Кувейт',                   text: 'Эль-Кувейт' },
    { flag: 'sa', key: 'Эр-Рияд',                      value: 'Эр-Рияд',                      text: 'Эр-Рияд' },
    { flag: 'ki', key: 'Южная Тарава',                 value: 'Южная Тарава',                 text: 'Южная Тарава' },
    { flag: 'ci', key: 'Ямусукро',                     value: 'Ямусукро',                     text: 'Ямусукро' },
    { flag: 'cm', key: 'Яунде',                        value: 'Яунде',                        text: 'Яунде' },
    { flag: 'us', key: 'Murray Hill',                  value: 'Murray Hill',                  text: 'Murray Hill' },
]

export const COUNTRY_OPTIONS = [                                                                               //
    { flag: 'au', key: 'Австралия',                          value: 'Австралия',                         text: 'Австралия' },
    { flag: 'at', key: 'Австрия',                            value: 'Австрия',                           text: 'Австрия' },
    { flag: 'az', key: 'Азербайджан',                        value: 'Азербайджан',                       text: 'Азербайджан' },
    { flag: 'al', key: 'Албания',                            value: 'Албания',                           text: 'Албания' },
    { flag: 'dz', key: 'Алжир',                              value: 'Алжир',                             text: 'Алжир' },
    { flag: 'ao', key: 'Ангола',                             value: 'Ангола',                            text: 'Ангола' },
    { flag: 'ad', key: 'Андорра',                            value: 'Андорра',                           text: 'Андорра' },
    { flag: 'ag', key: 'Антигуа и Барбуда',                  value: 'Антигуа и Барбуда',                 text: 'Антигуа и Барбуда' },
    { flag: 'ar', key: 'Аргентина',                          value: 'Аргентина',                         text: 'Аргентина' },
    { flag: 'am', key: 'Армения',                            value: 'Армения',                           text: 'Армения' },
    { flag: 'af', key: 'Афганистан',                         value: 'Афганистан',                        text: 'Афганистан' },
    { flag: 'bs', key: 'Багамы',                             value: 'Багамы',                            text: 'Багамы' },
    { flag: 'bd', key: 'Бангладеш',                          value: 'Бангладеш',                         text: 'Бангладеш' },
    { flag: 'bb', key: 'Барбадос',                           value: 'Барбадос',                          text: 'Барбадос' },
    { flag: 'bh', key: 'Бахрейн',                            value: 'Бахрейн',                           text: 'Бахрейн' },
    { flag: 'by', key: 'Беларусь',                           value: 'Беларусь',                          text: 'Беларусь' },
    { flag: 'bz', key: 'Белиз',                              value: 'Белиз',                             text: 'Белиз' },
    { flag: 'be', key: 'Бельгия',                            value: 'Бельгия',                           text: 'Бельгия' },
    { flag: 'bj', key: 'Бенин',                              value: 'Бенин',                             text: 'Бенин' },
    { flag: 'bg', key: 'Болгария',                           value: 'Болгария',                          text: 'Болгария' },
    { flag: 'bo', key: 'Боливия',                            value: 'Боливия',                           text: 'Боливия' },
    { flag: 'ba', key: 'Босния и Герцеговина',               value: 'Босния и Герцеговина',              text: 'Босния и Герцеговина' },
    { flag: 'bw', key: 'Ботсвана',                           value: 'Ботсвана',                          text: 'Ботсвана' },
    { flag: 'br', key: 'Бразилия',                           value: 'Бразилия',                          text: 'Бразилия' },
    { flag: 'bn', key: 'Бруней',                             value: 'Бруней',                            text: 'Бруней' },
    { flag: 'bf', key: 'Буркина Фасо',                       value: 'Буркина Фасо',                      text: 'Буркина Фасо' },
    { flag: 'bi', key: 'Бурунди',                            value: 'Бурунди',                           text: 'Бурунди' },
    { flag: 'bt', key: 'Бутан',                              value: 'Бутан',                             text: 'Бутан' },
    { flag: 'vu', key: 'Вануату',                            value: 'Вануату',                           text: 'Вануату' },
    { flag: 'va', key: 'Ватикан',                            value: 'Ватикан',                           text: 'Ватикан' },
    { flag: 'uk', key: 'Великобритания',                     value: 'Великобритания',                    text: 'Великобритания' },
    { flag: 'hu', key: 'Венгрия',                            value: 'Венгрия',                           text: 'Венгрия' },
    { flag: 've', key: 'Венесуэла',                          value: 'Венесуэла',                         text: 'Венесуэла' },
    { flag: 'tp', key: 'Восточный Тимор',                    value: 'Восточный Тимор',                   text: 'Восточный Тимор' },
    { flag: 'vn', key: 'Вьетнам',                            value: 'Вьетнам',                           text: 'Вьетнам' },
    { flag: 'ga', key: 'Габон',                              value: 'Габон',                             text: 'Габон' },
    { flag: 'ht', key: 'Гаити',                              value: 'Гаити',                             text: 'Гаити' },
    { flag: 'gy', key: 'Гайана',                             value: 'Гайана',                            text: 'Гайана' },
    { flag: 'gm', key: 'Гамбия',                             value: 'Гамбия',                            text: 'Гамбия' },
    { flag: 'gh', key: 'Гана',                               value: 'Гана',                              text: 'Гана' },
    { flag: 'gt', key: 'Гватемала',                          value: 'Гватемала',                         text: 'Гватемала' },
    { flag: 'gn', key: 'Гвинея',                             value: 'Гвинея',                            text: 'Гвинея' },
    { flag: 'gw', key: 'Гвинея-Бисау',                       value: 'Гвинея-Бисау',                      text: 'Гвинея-Бисау' },
    { flag: 'de', key: 'Германия',                           value: 'Германия',                          text: 'Германия' },
    { flag: 'hn', key: 'Гондурас',                           value: 'Гондурас',                          text: 'Гондурас' },
    { flag: 'gd', key: 'Гренада',                            value: 'Гренада',                           text: 'Гренада' },
    { flag: 'gr', key: 'Греция',                             value: 'Греция',                            text: 'Греция' },
    { flag: 'ge', key: 'Грузия',                             value: 'Грузия',                            text: 'Грузия' },
    { flag: 'dk', key: 'Дания',                              value: 'Дания',                             text: 'Дания' },
    { flag: 'dj', key: 'Джибути',                            value: 'Джибути',                           text: 'Джибути' },
    { flag: 'dm', key: 'Доминика',                           value: 'Доминика',                          text: 'Доминика' },
    { flag: 'do', key: 'Доминиканская Республика',           value: 'Доминиканская Республика',          text: 'Доминиканская Республика' },
    { flag: 'eg', key: 'Египет',                             value: 'Египет',                            text: 'Египет' },
    { flag: 'zm', key: 'Замбия',                             value: 'Замбия',                            text: 'Замбия' },
    { flag: 'zw', key: 'Зимбабве',                           value: 'Зимбабве',                          text: 'Зимбабве' },
    { flag: 'il', key: 'Израиль',                            value: 'Израиль',                           text: 'Израиль' },
    { flag: 'in', key: 'Индия',                              value: 'Индия',                             text: 'Индия' },
    { flag: 'id', key: 'Индонезия',                          value: 'Индонезия',                         text: 'Индонезия' },
    { flag: 'jo', key: 'Иордания',                           value: 'Иордания',                          text: 'Иордания' },
    { flag: 'iq', key: 'Ирак',                               value: 'Ирак',                              text: 'Ирак' },
    { flag: 'ir', key: 'Иран',                               value: 'Иран',                              text: 'Иран' },
    { flag: 'ie', key: 'Ирландия',                           value: 'Ирландия',                          text: 'Ирландия' },
    { flag: 'is', key: 'Исландия',                           value: 'Исландия',                          text: 'Исландия' },
    { flag: 'es', key: 'Испания',                            value: 'Испания',                           text: 'Испания' },
    { flag: 'it', key: 'Италия',                             value: 'Италия',                            text: 'Италия' },
    { flag: 'ye', key: 'Йемен',                              value: 'Йемен',                             text: 'Йемен' },
    { flag: 'cv', key: 'Кабо-Верде',                         value: 'Кабо-Верде',                        text: 'Кабо-Верде' },
    { flag: 'kz', key: 'Казахстан',                          value: 'Казахстан',                         text: 'Казахстан' },
    { flag: 'kh', key: 'Камбоджа',                           value: 'Камбоджа',                          text: 'Камбоджа' },
    { flag: 'cm', key: 'Камерун',                            value: 'Камерун',                           text: 'Камерун' },
    { flag: 'ca', key: 'Канада',                             value: 'Канада',                            text: 'Канада' },
    { flag: 'qa', key: 'Катар',                              value: 'Катар',                             text: 'Катар' },
    { flag: 'ke', key: 'Кения',                              value: 'Кения',                             text: 'Кения' },
    { flag: 'cy', key: 'Кипр',                               value: 'Кипр',                              text: 'Кипр' },
    { flag: 'kg', key: 'Киргизия',                           value: 'Киргизия',                          text: 'Киргизия' },
    { flag: 'ki', key: 'Кирибати',                           value: 'Кирибати',                          text: 'Кирибати' },
    { flag: 'cn', key: 'Китай',                              value: 'Китай',                             text: 'Китай' },
    { flag: 'co', key: 'Колумбия',                           value: 'Колумбия',                          text: 'Колумбия' },
    { flag: 'km', key: 'Коморы',                             value: 'Коморы',                            text: 'Коморы' },
    { flag: 'cd', key: 'Конго, демократическая республика',  value: 'Конго, демократическая республика', text: 'Конго, демократическая республика' },
    { flag: 'cg', key: 'Конго, республика',                  value: 'Конго, республика',                 text: 'Конго, республика' },
    { flag: 'cr', key: 'Коста-Рика',                         value: 'Коста-Рика',                        text: 'Коста-Рика' },
    { flag: 'ci', key: 'Кот-д’Ивуар',                        value: 'Кот-д’Ивуар',                       text: 'Кот-д’Ивуар' },
    { flag: 'cu', key: 'Куба',                               value: 'Куба',                              text: 'Куба' },
    { flag: 'kw', key: 'Кувейт',                             value: 'Кувейт',                            text: 'Кувейт' },
    { flag: 'la', key: 'Лаос',                               value: 'Лаос',                              text: 'Лаос' },
    { flag: 'lv', key: 'Латвия',                             value: 'Латвия',                            text: 'Латвия' },
    { flag: 'ls', key: 'Лесото',                             value: 'Лесото',                            text: 'Лесото' },
    { flag: 'lr', key: 'Либерия',                            value: 'Либерия',                           text: 'Либерия' },
    { flag: 'lb', key: 'Ливан',                              value: 'Ливан',                             text: 'Ливан' },
    { flag: 'ly', key: 'Ливия',                              value: 'Ливия',                             text: 'Ливия' },
    { flag: 'lt', key: 'Литва',                              value: 'Литва',                             text: 'Литва' },
    { flag: 'li', key: 'Лихтенштейн',                        value: 'Лихтенштейн',                       text: 'Лихтенштейн' },
    { flag: 'lu', key: 'Люксембург',                         value: 'Люксембург',                        text: 'Люксембург' },
    { flag: 'mu', key: 'Маврикий',                           value: 'Маврикий',                          text: 'Маврикий' },
    { flag: 'mr', key: 'Мавритания',                         value: 'Мавритания',                        text: 'Мавритания' },
    { flag: 'mg', key: 'Мадагаскар',                         value: 'Мадагаскар',                        text: 'Мадагаскар' },
    { flag: 'mk', key: 'Македония',                          value: 'Македония',                         text: 'Македония' },
    { flag: 'mw', key: 'Малави',                             value: 'Малави',                            text: 'Малави' },
    { flag: 'my', key: 'Малайзия',                           value: 'Малайзия',                          text: 'Малайзия' },
    { flag: 'ml', key: 'Мали',                               value: 'Мали',                              text: 'Мали' },
    { flag: 'mv', key: 'Мальдивы',                           value: 'Мальдивы',                          text: 'Мальдивы' },
    { flag: 'mt', key: 'Мальта',                             value: 'Мальта',                            text: 'Мальта' },
    { flag: 'ma', key: 'Марокко',                            value: 'Марокко',                           text: 'Марокко' },
    { flag: 'mh', key: 'Маршалловы Острова',                 value: 'Маршалловы Острова',                text: 'Маршалловы Острова' },
    { flag: 'mx', key: 'Мексика',                            value: 'Мексика',                           text: 'Мексика' },
    { flag: 'mz', key: 'Мозамбик',                           value: 'Мозамбик',                          text: 'Мозамбик' },
    { flag: 'md', key: 'Молдавия',                           value: 'Молдавия',                          text: 'Молдавия' },
    { flag: 'mc', key: 'Монако',                             value: 'Монако',                            text: 'Монако' },
    { flag: 'mn', key: 'Монголия',                           value: 'Монголия',                          text: 'Монголия' },
    { flag: 'mm', key: 'Мьянма',                             value: 'Мьянма',                            text: 'Мьянма' },
    { flag: 'na', key: 'Намибия',                            value: 'Намибия',                           text: 'Намибия' },
    { flag: 'nr', key: 'Науру',                              value: 'Науру',                             text: 'Науру' },
    { flag: 'np', key: 'Непал',                              value: 'Непал',                             text: 'Непал' },
    { flag: 'ne', key: 'Нигер',                              value: 'Нигер',                             text: 'Нигер' },
    { flag: 'ng', key: 'Нигерия',                            value: 'Нигерия',                           text: 'Нигерия' },
    { flag: 'nl', key: 'Нидерланды',                         value: 'Нидерланды',                        text: 'Нидерланды' },
    { flag: 'ni', key: 'Никарагуа',                          value: 'Никарагуа',                         text: 'Никарагуа' },
    { flag: 'nz', key: 'Новая Зеландия',                     value: 'Новая Зеландия',                    text: 'Новая Зеландия' },
    { flag: 'no', key: 'Норвегия',                           value: 'Норвегия',                          text: 'Норвегия' },
    { flag: 'ae', key: 'Объединенные Арабские Эмираты',      value: 'Объединенные Арабские Эмираты',     text: 'Объединенные Арабские Эмираты' },
    { flag: 'om', key: 'Оман',                               value: 'Оман',                              text: 'Оман' },
    { flag: 'pk', key: 'Пакистан',                           value: 'Пакистан',                          text: 'Пакистан' },
    { flag: 'pw', key: 'Палау',                              value: 'Палау',                             text: 'Палау' },
    { flag: 'pa', key: 'Панама',                             value: 'Панама',                            text: 'Панама' },
    { flag: 'pg', key: 'Папуа - Новая Гвинея',               value: 'Папуа - Новая Гвинея',              text: 'Папуа - Новая Гвинея' },
    { flag: 'py', key: 'Парагвай',                           value: 'Парагвай',                          text: 'Парагвай' },
    { flag: 'pe', key: 'Перу',                               value: 'Перу',                              text: 'Перу' },
    { flag: 'pl', key: 'Польша',                             value: 'Польша',                            text: 'Польша' },
    { flag: 'pt', key: 'Португалия',                         value: 'Португалия',                        text: 'Португалия' },
    { flag: 'ru', key: 'Россия',                             value: 'Россия',                            text: 'Россия' },
    { flag: 'rw', key: 'Руанда',                             value: 'Руанда',                            text: 'Руанда' },
    { flag: 'ro', key: 'Румыния',                            value: 'Румыния',                           text: 'Румыния' },
    { flag: 'sv', key: 'Сальвадор',                          value: 'Сальвадор',                         text: 'Сальвадор' },
    { flag: 'ws', key: 'Самоа',                              value: 'Самоа',                             text: 'Самоа' },
    { flag: 'sm', key: 'Сан-Марино',                         value: 'Сан-Марино',                        text: 'Сан-Марино' },
    { flag: 'st', key: 'Сан-Томе и Принсипи',                value: 'Сан-Томе и Принсипи',               text: 'Сан-Томе и Принсипи' },
    { flag: 'sa', key: 'Саудовская Аравия',                  value: 'Саудовская Аравия',                 text: 'Саудовская Аравия' },
    { flag: 'sz', key: 'Свазиленд',                          value: 'Свазиленд',                         text: 'Свазиленд' },
    { flag: 'kp', key: 'Северная Корея',                     value: 'Северная Корея',                    text: 'Северная Корея' },
    { flag: 'sc', key: 'Сейшелы',                            value: 'Сейшелы',                           text: 'Сейшелы' },
    { flag: 'sn', key: 'Сенегал',                            value: 'Сенегал',                           text: 'Сенегал' },
    { flag: 'vc', key: 'Сент-Винсент и Гренадины',           value: 'Сент-Винсент и Гренадины',          text: 'Сент-Винсент и Гренадины' },
    { flag: 'kn', key: 'Сент-Китс и Невис',                  value: 'Сент-Китс и Невис',                 text: 'Сент-Китс и Невис' },
    { flag: 'lc', key: 'Сент-Люсия',                         value: 'Сент-Люсия',                        text: 'Сент-Люсия' },
    { flag: 'cs', key: 'Сербия',                             value: 'Сербия',                            text: 'Сербия' },
    { flag: 'sg', key: 'Сингапур',                           value: 'Сингапур',                          text: 'Сингапур' },
    { flag: 'sy', key: 'Сирия',                              value: 'Сирия',                             text: 'Сирия' },
    { flag: 'sk', key: 'Словакия',                           value: 'Словакия',                          text: 'Словакия' },
    { flag: 'si', key: 'Словения',                           value: 'Словения',                          text: 'Словения' },
    { flag: 'us', key: 'Соединенные Штаты Америки',          value: 'Соединенные Штаты Америки',         text: 'Соединенные Штаты Америки' },
    { flag: 'sb', key: 'Соломоновы Острова',                 value: 'Соломоновы Острова',                text: 'Соломоновы Острова' },
    { flag: 'so', key: 'Сомали',                             value: 'Сомали',                            text: 'Сомали' },
    { flag: 'zw', key: 'Судан',                              value: 'Судан',                             text: 'Судан' },
    { flag: 'sr', key: 'Суринам',                            value: 'Суринам',                           text: 'Суринам' },
    { flag: 'sl', key: 'Сьерра-Леоне',                       value: 'Сьерра-Леоне',                      text: 'Сьерра-Леоне' },
    { flag: 'tj', key: 'Таджикистан',                        value: 'Таджикистан',                       text: 'Таджикистан' },
    { flag: 'th', key: 'Таиланд',                            value: 'Таиланд',                           text: 'Таиланд' },
    { flag: 'tz', key: 'Танзания',                           value: 'Танзания',                          text: 'Танзания' },
    { flag: 'tg', key: 'Того',                               value: 'Того',                              text: 'Того' },
    { flag: 'to', key: 'Тонга',                              value: 'Тонга',                             text: 'Тонга' },
    { flag: 'tt', key: 'Тринидад и Тобаго',                  value: 'Тринидад и Тобаго',                 text: 'Тринидад и Тобаго' },
    { flag: 'tv', key: 'Тувалу',                             value: 'Тувалу',                            text: 'Тувалу' },
    { flag: 'tn', key: 'Тунис',                              value: 'Тунис',                             text: 'Тунис' },
    { flag: 'tm', key: 'Туркмения',                          value: 'Туркмения',                         text: 'Туркмения' },
    { flag: 'tr', key: 'Турция',                             value: 'Турция',                            text: 'Турция' },
    { flag: 'ug', key: 'Уганда',                             value: 'Уганда',                            text: 'Уганда' },
    { flag: 'uz', key: 'Узбекистан',                         value: 'Узбекистан',                        text: 'Узбекистан' },
    { flag: 'ua', key: 'Украина',                            value: 'Украина',                           text: 'Украина' },
    { flag: 'uy', key: 'Уругвай',                            value: 'Уругвай',                           text: 'Уругвай' },
    { flag: 'fm', key: 'Федеративные штаты Микронезии',      value: 'Федеративные штаты Микронезии',     text: 'Федеративные штаты Микронезии' },
    { flag: 'fj', key: 'Фиджи',                              value: 'Фиджи',                             text: 'Фиджи' },
    { flag: 'ph', key: 'Филиппины',                          value: 'Филиппины',                         text: 'Филиппины' },
    { flag: 'fi', key: 'Финляндия',                          value: 'Финляндия',                         text: 'Финляндия' },
    { flag: 'fr', key: 'Франция',                            value: 'Франция',                           text: 'Франция' },
    { flag: 'ht', key: 'Хорватия',                           value: 'Хорватия',                          text: 'Хорватия' },
    { flag: 'cf', key: 'Центрально-Африканская Республика',  value: 'Центрально-Африканская Республика', text: 'Центрально-Африканская Республика' },
    { flag: 'td', key: 'Чад',                                value: 'Чад',                               text: 'Чад' },
    { flag: 'yu', key: 'Черногория',                         value: 'Черногория',                        text: 'Черногория' },
    { flag: 'cz', key: 'Чехия',                              value: 'Чехия',                             text: 'Чехия' },
    { flag: 'cl', key: 'Чили',                               value: 'Чили',                              text: 'Чили' },
    { flag: 'ch', key: 'Швейцария',                          value: 'Швейцария',                         text: 'Швейцария' },
    { flag: 'se', key: 'Швеция',                             value: 'Швеция',                            text: 'Швеция' },
    { flag: 'lk', key: 'Шри-Ланка',                          value: 'Шри-Ланка',                         text: 'Шри-Ланка' },
    { flag: 'ec', key: 'Эквадор',                            value: 'Эквадор',                           text: 'Эквадор' },
    { flag: 'gq', key: 'Экваториальная Гвинея',              value: 'Экваториальная Гвинея',             text: 'Экваториальная Гвинея' },
    { flag: 'er', key: 'Эритрея',                            value: 'Эритрея',                           text: 'Эритрея' },
    { flag: 'ee', key: 'Эстония',                            value: 'Эстония',                           text: 'Эстония' },
    { flag: 'et', key: 'Эфиопия',                            value: 'Эфиопия',                           text: 'Эфиопия' },
    { flag: 'kr', key: 'Южная Корея',                        value: 'Южная Корея',                       text: 'Южная Корея' },
    { flag: 'za', key: 'Южно-Африканская Республика',        value: 'Южно-Африканская Республика',       text: 'Южно-Африканская Республика' },
    { flag: 'jm', key: 'Ямайка',                             value: 'Ямайка',                            text: 'Ямайка' },
    { flag: 'jp', key: 'Япония',                             value: 'Япония',                            text: 'Япония' }
]
